# Generated by Django 4.1 on 2023-02-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('UserEmail', models.EmailField(max_length=50)),
                ('Userpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
