# Generated by Django 4.1 on 2023-02-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
